version: "3.7"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - app-network

  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy # espera o banco estar pronto
    environment:
      DATABASE_URL: postgresql://postgres:secret@postgres:5432/mydb
      # ↑ usa o nome do serviço "postgres", não localhost!
    ports:
      - "8000:8000"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
